[package]
name = "asciiarena"
version = "0.1.0"
authors = ["lemunozm <lemunozm@gmail.com>"]
edition = "2018"

[dependencies]
message-io = { git = 'https://github.com/lemunozm/message-io', branch = 'master' }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"
colored = "1.9.3"
clap ="2.33.1"
